### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jamesdolezal** [adamshephard/OMTscoring_inference#2]
Hi again - thanks again for making your code available! We'd like to work with your pipeline for research applications, but this repository does not have a license specified, which precludes this code from use. Would you consider adding a license?

Thank you,
James

**Comment by adamshephard** [comment]
Hi James,

My apologies for my delay in response. I am pleased to hear you are interested in using this pipeline for research. Feel free to get in contact with me for more details. I have now added the license as suggested. Thanks!

Best,
Adam
